### ISSUE TITLE
mb_index undefined in Interleaved 1F1B

### ISSUE THREAD

**Issue by kwen2501** [pytorch/PiPPy#1050]
https://github.com/pytorch/PiPPy/blob/9cd29d17324a53b1342c2b6fc5eeef5f5405ec49/pippy/PipelineSchedule.py#L572-L598

`mb_index` is only defined in condition `if step < warmup_steps`, not in other conditions.

**Comment by kwen2501** [comment]
btw, @H-Huang, can we just increment `mb_index` naturally? 
And should we have `fwd_mb_index` and `bwd_mb_index` separately?

**Comment by H-Huang** [comment]
> Related, does this change to 1F1B look correct to you?
https://github.com/pytorch/PiPPy/pull/1052

Change looks good

> can we just increment mb_index naturally? And should we have fwd_mb_index and bwd_mb_index separately?

yeah that would be fine. Each stage in the schedule would need to track its own fwd_mb_index and bwd_mb_index
