### ISSUE TITLE
Manual PP stage gives inconsistent output shape for first stage

### ISSUE THREAD

**Issue by wconstab** [pytorch/PiPPy#1054]
Found this as i was developing a test for PP+FSDP, but disabled the FSDP parts and found the same issue remains.  Repro command and test code are in this gist:
https://gist.github.com/wconstab/74a3354f31b2b63cec7f4213682360a1

after disabling FSDP its still running on 4 gpus but doing 2 PP stages so rank0,1 are paired, and rank 2,3 are paired.  just look at 0,1 and ignore 2,3.

The error message is 
```
RuntimeError: 
        Failed to run stage backward:
        Stage output: ('Tensor(torch.Size([10]), grad=True)',)
        Output gradient: ['Tensor(torch.Size([1, 10]), grad=False)']
        Input: ['Tensor(torch.Size([1, 10]), grad=False)']
```

Tracing it back, these logs show that during forward, stage 0 computes a different than expected output shape.  It appears to drop the (1,) dim for some reason.

```
[rank0]:V0411 17:27:30.063000 140289829430400 ../pippy/pippy/PipelineSchedule.py:231] [0] Forwarded microbatch 0                                                                       
DEBUG:pippy.PipelineSchedule:[0] Forwarded microbatch 0                                                                                                                                           
[rank1]:V0411 17:27:30.064000 140419639100544 ../pippy/pippy/PipelineStage.py:220] [1] Forwarded chunk 0, outputs: Tensor(torch.Size([1, 10]), grad=True)
DEBUG:pippy.PipelineStage:[1] Forwarded chunk 0, outputs: Tensor(torch.Size([1, 10]), grad=True)                                                                                                  
[rank1]:V0411 17:27:30.064000 140419639100544 ../pippy/pippy/PipelineSchedule.py:231] [1] Forwarded microbatch 0                                        
DEBUG:pippy.PipelineSchedule:[1] Forwarded microbatch 0                                                                                                                                           
[rank0]:V0411 17:27:30.064000 140289829430400 ../pippy/pippy/PipelineStage.py:220] [0] Forwarded chunk 1, outputs: Tensor(torch.Size([10]), grad=True)
DEBUG:pippy.PipelineStage:[0] Forwarded chunk 1, outputs: Tensor(torch.Size([10]), grad=True)
```

Adding some debug code to the test script, the partial model chunk fed to stage 0 seems to give the expected output shape:
`0 : torch.Size([1, 10]) `

**Comment by wconstab** [comment]
ok i think what's going on is some mishandling of the *args operator.

Based on this experiment
```
>>> import torch
>>> x = torch.ones((2, 4))
>>> def foo(*args): print(args)
... 
>>> args = x
>>> foo(*x)
(tensor([1., 1., 1., 1.]), tensor([1., 1., 1., 1.]))
```

`forward_one_chunk` does 
```
        # Compute forward
        try:
            output = self.forward_maybe_with_nosync(
                *composite_args, **composite_kwargs
            )
```
but composite_args is just a tensor here, not wrapped in a tuple or anything.

going up a layer in the stack, we call forward_one_chunk via 

```
 output = self._stage.forward_one_chunk(arg_mbs[i], kwarg_mbs[i])  # type: ignore[index]
```

where arg_mbs is what the user provided.

in my case i provided microbatches as [tensor(), tensor(), ...] 

Is the contract clear for how microbatches should be provided? Not sure if i'm supposed to be putting each one in a tuple.  (or if so, we should do more validation of that.

**Comment by H-Huang** [comment]
Yeah this looks like an issue where `*args` is expected to be a list of args (`[tensor_arg1, tensor_arg2, tensor_arg3]`), but in this case `args` is just a single tensor which is getting expanded. This was due to the change of merging the manual and tracing forwards, whereas previously manual support both `args=single tensor` and `args=list of tensors` 

So the quick fix for you is to change microbatches to `[[tensor()], [tensor()], ...]`, I think we only want to support list of args going forward so I will add validation, test cases, and erroring on behalf of the program if the input is unexpected type (since a tensor getting expanded silently is very confusing!)
