### ISSUE TITLE
ImportError: cannot import name 'pipeline' from 'pippy'

### ISSUE THREAD

**Issue by bob020416** [pytorch/PiPPy#1123]
Do anyone have the same issue when trying to run the example in PiPPy? 
I cannot import part of the module such as pipeline, Splitpoint, and more ...
I correctly set up the enviroment and even try to handcraft hese functions 

But i still cannot find a correct way to import these modules and functions
Is there any issue with  these api?　how can i corrrect it ?

issue:
```from pippy import pipeline, annotate_split_points, Pipe, SplitPoint```
failed with ``` ImportError: cannot import name 'pipeline' from 'pippy' (/home/bob020416/miniconda3/envs/DL/lib/python3.9/site-packages/pippy/__init__.py)```

**Comment by kwen2501** [comment]
Hi, sorry about the break. 
We recently migrated PiPPy into pytorch as `torch.distributed.pipelining`, to be released in PyTorch 2.4.
In the process, a couple APIs have minor changes too. 
We will add a notice for this migration on this GitHub front page soon.

I just migrated some of our HF examples to use the new API in torch. Hope that helps.
https://github.com/pytorch/PiPPy/pull/1124
