### ISSUE TITLE
[Question] Is the current implementation efficient?

### ISSUE THREAD

**Issue by jq-wei** [pytorch/PiPPy#1144]
Hi, 

I have a question about the order of cutting the model. 

In the [pippy_llama.py](https://github.com/pytorch/PiPPy/blob/main/examples/llama/pippy_llama.py#L24), the model is first moved to all the devices with the full copy, and then cut it. This does not really solve the problem that model can not fit into one device, right? A more effective way would be load the model to say CPU, and partition, then move only part of the model to the devices. 

Let me know if my understanding is correct, and if this is how it implemented on other cases. 

Thanks!

**Comment by jq-wei** [comment]
I found the cpu_init.

**Comment by Noblezhong** [comment]
Do u run cpu_init.py successfully on single server? I am also interested in setting LLM pipeline on a multi-GPU device, I want to consult some question to u! thanks
