### ISSUE TITLE
init_empty_weights only works with torchrun and is very slow

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/PiPPy#786]
Running the HF inference example, for "cerebras/Cerebras-GPT-13B" with `init_empty_weights` can run only with `torchrun` and as the result init time is ~6x slower on a machine with 4 gpu. 846s vs 134s (from_pretrained(hf_model)).

Error log without torchrun,  https://gist.github.com/HamidShojanazeri/f5c4da7b21717641625015cba04bed99

**Comment by HamidShojanazeri** [comment]
cc : @jiqing-feng

**Comment by jiqing-feng** [comment]
Hi @HamidShojanazeri . I think you don't need to use init_empty_weights if you only run one process. I will have a look at the init time. BTW, are you running https://github.com/pytorch/PiPPy/blob/main/examples/inference/hf_generate.py ?

**Comment by HamidShojanazeri** [comment]
BTW added you in Slack to discuss easier pls let me know if you had issues with the invite.

**Comment by jiqing-feng** [comment]
@HamidShojanazeri Sorry for the delay, I am quite busy recently. I only use Teams in my work and I just try to use Slack but didn't find any invitation, could you please invite me again? Thanks!

**Comment by kwen2501** [comment]
Fixed via #790, #792, #793.
Previously we have some code that serializes stage initialization. Now it is remove.
According to @HamidShojanazeri, loading 30B model on 4 GPUs takes about 17 second now.
