### ISSUE TITLE
Support for UNet1D and UNet2D models?

### ISSUE THREAD

**Issue by prajwal1210** [pytorch/PiPPy#940]
Is it possible to support UNet models with PiPPy?

**Comment by kwen2501** [comment]
Can you give us a pointer to the UNet models you refer to? Ideally model code from which we can build the model.

**Comment by prajwal1210** [comment]
HF Model Page: https://huggingface.co/docs/diffusers/en/api/models/unet2d
Github Code: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_2d.py

**Comment by kwen2501** [comment]
Do you mind taking a look at #943? Thanks!

**Comment by prajwal1210** [comment]
This looks nice. Is it possible to have a training example as well along with eval?
